

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    env_file:
      - ./Backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps nodemon detect changes in some Docker environments

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true # Allows React to keep running in the foreground
    tty: true
    environment:
      - VITE_WATCH_USEPOLLING=true
      - BACKEND_URL=http://backend:3000
